osx_image: xcode7.3
language: objective-c

script:
  - pod repo update
  - open -b com.apple.iphonesimulator
  - set -o pipefail && env NSUnbufferedIO=YES
    xcodebuild test
    -workspace ReaderExample.xcworkspace
    -scheme ReaderExample
    -sdk iphonesimulator
    -destination "platform=iOS Simulator,name=iPhone 6s" | xcpretty
