osx_image: xcode7.3
language: objective-c

script:
  - open -b com.apple.iphonesimulator
  - sed -i -e 's/git@github.com:/git:\/\/github.com\//' Podfile
  - set -o pipefail && env NSUnbufferedIO=YES
    xcodebuild test
    -workspace ReaderExample.xcworkspace
    -scheme ReaderExample
    -sdk iphonesimulator
    -destination "platform=iOS Simulator,name=iPhone 6s" | xcpretty
